//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("audio.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("audio2.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("bin/debug/depthbasics-wpf.vshost.exe")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("obj/debug/temppe/properties.resources.designer.cs.dll")]


